global:
  scrape_interval: 15s  # Как часто собирать метрики
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'synthetic-human-app'  # Твоё приложение
    metrics_path: '/actuator/prometheus'  # Путь к метрикам
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]  # Для Mac/Windows; для Linux: 'your-host-ip:8080'
        labels:
          application: 'synthetic-human-core-starter'